import { definePlugin, type PrimioPlugin } from './index.js'

const plugin = (id: string, name: string, description: string, features: Partial<PrimioPlugin>) =>
  definePlugin({
    schemaVersion: 2,
    id: 'primio.' + id,
    name,
    description,
    author: 'Primio',
    version: '1.0.0',
    permissions: [],
    ...features,
  })
const theme = (
  id: string,
  name: string,
  description: string,
  background: string,
  surface: string,
  accent: string,
  text: string,
  muted: string,
  radius = 16,
) =>
  plugin(id, name, description, {
    category: 'theme',
    permissions: ['theme'],
    theme: { background, surface, accent, text, muted, radius },
  })
export const officialPlugins: PrimioPlugin[] = [
  plugin('neo-graphite', 'Neo Graphite', 'Un graphite doux, des commandes sculptées et des creux délicats. Un thème néomorphique complet.', {
    category: 'theme', permissions: ['theme'],
    theme: {
      material: 'neumorphic', colorScheme: 'dark',
      background: '#282B30', surface: '#282B30', accent: '#E6D3AC',
      text: '#F3F0E8', muted: '#BCC0C8', border: '#646A73',
      shadowLight: '#383D45', shadowDark: '#191C20',
      radius: 18, glassOpacity: 1,
    },
  }),
  theme(
    'graphite',
    'Graphite',
    'Le verre fumé et les reflets ivoire de Primio.',
    '#101110',
    '#1D1E1C',
    '#DAD4C5',
    '#F3F1EB',
    '#B7B8B1',
  ),
  theme(
    'midnight',
    'Midnight',
    'Bleu nuit profond et accents argentés.',
    '#0B1220',
    '#172236',
    '#B7D6FF',
    '#EEF4FF',
    '#AABBD2',
  ),
  theme(
    'sakura',
    'Sakura',
    'Prune sombre et touches de rose poudré.',
    '#19121A',
    '#2B202D',
    '#F2BCD8',
    '#FFF0F8',
    '#CAB5C6',
    20,
  ),
  theme(
    'forest',
    'Forest',
    'Vert forêt, sauge et surfaces douces.',
    '#0E1713',
    '#1D2B23',
    '#B7D8AB',
    '#EFF6EC',
    '#AEBDAD',
  ),
  theme(
    'amber',
    'Amber',
    'Brun profond et accents ambrés.',
    '#19130E',
    '#2B2119',
    '#F1CA8C',
    '#FFF4E5',
    '#C7B6A0',
  ),
  theme(
    'oled',
    'OLED',
    'Noir pur et contraste renforcé.',
    '#000000',
    '#121212',
    '#FFFFFF',
    '#FFFFFF',
    '#C4C4C4',
    12,
  ),
  plugin(
    'anime-sources',
    'Anime VOSTFR',
    'Privilégier les sources VOSTFR et MULTI, masquer CAM et TS.',
    {
      category: 'sources',
      permissions: ['sources'],
      sources: { prefer: ['VOSTFR', 'MULTI', 'JAP'], hide: ['CAM', 'TELESYNC'] },
    },
  ),
  plugin('french-sources', 'Cinéma VF', 'Privilégier VFF, TRUEFRENCH puis MULTI.', {
    category: 'sources',
    permissions: ['sources'],
    sources: { prefer: ['VFF', 'TRUEFRENCH', 'MULTI'], hide: ['CAM', 'TELESYNC'] },
  }),
  plugin(
    'quality-sources',
    'Haute définition',
    'Classer les sources 2160p puis 1080p en premier.',
    {
      category: 'sources',
      permissions: ['sources'],
      sources: { prefer: ['2160p', '4K', '1080p'], hide: ['CAM', 'TELESYNC'] },
    },
  ),
  plugin('compact', 'Bibliothèque compacte', 'Cinq colonnes et affiches compactes.', {
    category: 'library',
    permissions: ['layout'],
    layout: { columns: 5, density: 'compact' },
  }),
  plugin('posters', 'Galerie d’affiches', 'Quatre colonnes, sans nom ni date sous les affiches.', {
    category: 'library',
    permissions: ['layout'],
    layout: { columns: 4, labels: false },
  }),
  plugin(
    'comfortable',
    'Lecture confortable',
    'Trois colonnes, texte agrandi et animations réduites.',
    {
      category: 'accessibility',
      permissions: ['layout', 'accessibility'],
      layout: { columns: 3, density: 'comfortable' },
      accessibility: { fontScale: 1.15, reduceMotion: true },
    },
  ),
  plugin('calm', 'Sans animations', 'Réduire les mouvements dans l’interface.', {
    category: 'accessibility',
    permissions: ['accessibility'],
    accessibility: { reduceMotion: true },
  }),
  plugin(
    'anti-spoilers',
    'Anti-spoilers',
    'Masquer les titres, images et résumés des épisodes non vus. Dévoilement à la demande.',
    { category: 'library', permissions: ['spoilers'], spoilers: { hideUnwatched: true } },
  ),
  plugin(
    'middle-earth',
    'La Terre du Milieu',
    'Deux parcours : ordre de sortie ou chronologie de l’histoire.',
    {
      category: 'library',
      permissions: ['watchOrder'],
      watchOrder: [
        {
          id: 'release',
          title: 'La Terre du Milieu · Sortie',
          order: 'release',
          entries: [
            { id: 'tt0120737', type: 'movie', name: 'The Fellowship of the Ring' },
            { id: 'tt0167261', type: 'movie', name: 'The Two Towers' },
            { id: 'tt0167260', type: 'movie', name: 'The Return of the King' },
            { id: 'tt0903624', type: 'movie', name: 'An Unexpected Journey' },
            { id: 'tt1170358', type: 'movie', name: 'The Desolation of Smaug' },
            { id: 'tt2310332', type: 'movie', name: 'The Battle of the Five Armies' },
          ],
        },
        {
          id: 'chronology',
          title: 'La Terre du Milieu · Chronologie',
          order: 'chronological',
          entries: [
            { id: 'tt0903624', type: 'movie', name: 'An Unexpected Journey' },
            { id: 'tt1170358', type: 'movie', name: 'The Desolation of Smaug' },
            { id: 'tt2310332', type: 'movie', name: 'The Battle of the Five Armies' },
            { id: 'tt0120737', type: 'movie', name: 'The Fellowship of the Ring' },
            { id: 'tt0167261', type: 'movie', name: 'The Two Towers' },
            { id: 'tt0167260', type: 'movie', name: 'The Return of the King' },
          ],
        },
      ],
    },
  ),
  plugin('star-wars', 'Star Wars', 'Les films Star Wars dans une collection, en ordre chronologique ou de sortie.', {
    version: '1.1.0',
    category: 'library',
    permissions: ['watchOrder'],
    watchOrder: [
      {
        id: 'chronology', title: 'Star Wars · Chronologie', order: 'chronological',
        entries: [
          ['tt0120915', 'The Phantom Menace'],
          ['tt0121765', 'Attack of the Clones'],
          ['tt1185834', 'Star Wars: The Clone Wars'],
          ['tt0121766', 'Revenge of the Sith'],
          ['tt3778644', 'Solo: A Star Wars Story'],
          ['tt3748528', 'Rogue One: A Star Wars Story'],
          ['tt0076759', 'A New Hope'],
          ['tt0080684', 'The Empire Strikes Back'],
          ['tt0086190', 'Return of the Jedi'],
          ['tt30825738', 'The Mandalorian and Grogu'],
          ['tt2488496', 'The Force Awakens'],
          ['tt2527336', 'The Last Jedi'],
          ['tt2527338', 'The Rise of Skywalker'],
        ].map(([id, name]) => ({ id, name, type: 'movie' as const })),
      },
      {
        id: 'release',
        title: 'Star Wars · Sortie',
        order: 'release',
        entries: [
          ['tt0076759', 'A New Hope'],
          ['tt0080684', 'The Empire Strikes Back'],
          ['tt0086190', 'Return of the Jedi'],
          ['tt0120915', 'The Phantom Menace'],
          ['tt0121765', 'Attack of the Clones'],
          ['tt0121766', 'Revenge of the Sith'],
          ['tt1185834', 'Star Wars: The Clone Wars'],
          ['tt2488496', 'The Force Awakens'],
          ['tt3748528', 'Rogue One: A Star Wars Story'],
          ['tt2527336', 'The Last Jedi'],
          ['tt3778644', 'Solo: A Star Wars Story'],
          ['tt2527338', 'The Rise of Skywalker'],
          ['tt30825738', 'The Mandalorian and Grogu'],
        ].map(([id, name]) => ({ id, name, type: 'movie' as const })),
      },
    ],
  }),

  plugin('subtle-cinema', 'Salle obscure', 'Un thème charbon aux accents cuivre, pensé pour les soirées cinéma.', {
    category: 'theme', permissions: ['theme'],
    theme: { background: '#0E1012', surface: '#1C2024', accent: '#E6B58C', text: '#F6EFE8', muted: '#C4BCB4', radius: 12 },
  }),
  plugin('readable', 'Lisibilité', 'Texte agrandi, contraste clair et affiches espacées pour parcourir votre bibliothèque confortablement.', {
    category: 'accessibility', permissions: ['accessibility', 'layout'],
    accessibility: { fontScale: 1.25, reduceMotion: true }, layout: { columns: 3, density: 'comfortable', labels: true },
  }),
  plugin('original-audio', 'Version originale', 'Faire remonter les sources en langue originale et les éditions multilingues.', {
    category: 'sources', permissions: ['sources'], sources: { prefer: ['VOST', 'MULTI', 'DUAL'], hide: ['CAM', 'TELESYNC'] },
  }),
  plugin('animation-classics', 'Les débuts de Pixar', 'Un parcours des premiers longs métrages Pixar, dans leur ordre de sortie.', {
    category: 'library', permissions: ['watchOrder'], watchOrder: [{
      id: 'release', title: 'Les débuts de Pixar', order: 'release', entries: [
        ['tt0114709', 'Toy Story'], ['tt0120623', 'A Bug’s Life'], ['tt0120363', 'Toy Story 2'],
        ['tt0198781', 'Monsters, Inc.'], ['tt0266543', 'Finding Nemo'], ['tt0317705', 'The Incredibles'],
        ['tt0317219', 'Cars'], ['tt0382932', 'Ratatouille'], ['tt0910970', 'WALL·E'], ['tt1049413', 'Up'],
      ].map(([id,name]) => ({id,name,type:'movie' as const})),
    }],
  }),
]
