const regions: Record<string, string> = {
  en: 'gb',
  eng: 'gb',
  fr: 'fr',
  fra: 'fr',
  fre: 'fr',
  de: 'de',
  deu: 'de',
  ger: 'de',
  es: 'es',
  spa: 'es',
  pt: 'pt',
  por: 'pt',
  ja: 'jp',
  jpn: 'jp',
  ko: 'kr',
  kor: 'kr',
  zh: 'cn',
  zho: 'cn',
  chi: 'cn',
  'zh-Hans': 'cn',
  'zh-Hant': 'tw',
  ita: 'it',
  ara: 'sa',
  hin: 'in',
  rus: 'ru',
  ukr: 'ua',
  pol: 'pl',
  nld: 'nl',
  tur: 'tr',
  swe: 'se',
  dan: 'dk',
  nor: 'no',
  fin: 'fi',
  ell: 'gr',
  ces: 'cz',
  ron: 'ro',
  heb: 'il',
  tha: 'th',
  vie: 'vn',
  ind: 'id',
  msa: 'my',
}
export function LanguageFlag({ code }: { code: string }) {
  const region = regions[code]
  return region ? <img className="language-flag" src={`/flags/${region}.svg`} alt="" /> : null
}
