controls=command:arrow_back:quit?Back,gap,command:remove:script-binding primio/back?Back,play-pause,command:add:script-binding primio/forward?Forward,gap,space,command:playlist_play:script-binding primio/episodes?Episodes,gap,audio,subtitles,command:format_size:script-binding primio/style?Subtitle style,gap,fullscreen
controls_size=34
controls_margin=12
controls_spacing=8
top_bar=no-border
top_bar_controls=right
top_bar_size=44
top_bar_title=yes
top_bar_alt_title=
timeline_style=bar
timeline_size=26
timeline_border=0
progress=never
border_radius=12
menu_item_height=44
menu_min_width=360
color=foreground=dad4c5,foreground_text=101110,background=171916,background_text=f3f1eb,window_border=35372f,curtain=101110,success=dad4c5,error=e68b83,match=dad4c5,heatmap=d6ceb0
opacity=timeline=0.75,position=1,chapters=0.7,slider=0.75,slider_gauge=1,controls=0.45,speed=0.8,menu=0.96,submenu=0.8,border=0.4,title=1,tooltip=1,curtain=0.5,idle_indicator=0,buffering_indicator=0.2,pause_indicator=0
autoload=no
pause_indicator=never
languages=en
